version: "3"
services:
  guifi-drupal:
    image: guifi/drupal-guifi:drupal6
    environment:
      GUIFI_DB: guifidev
      DRUPAL_ADMIN: admin
      DRUPAL_ADMIN_PWD: drupal
      GUIFI_USER_DB: guifi
      GUIFI_USER_DB_PWD: guifi
      XDEBUG_PORT: 9000
      GUIFI_URL: http://dev.guifi.net/static/
    links:
      - database
      - gmaps
    volumes:
      - ./guifi-web:/usr/share/drupal/guifi-web/
    ports:
      - 8080:80
    depends_on:
      - database

  database:
    image: "mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: guifidev
      MYSQL_USER: guifi
      MYSQL_PASSWORD: guifi
    volumes:
      - ./database:/var/lib/mysql

  myadmin:
    image: "phpmyadmin/phpmyadmin"
    links:
      - database:db
    ports:
      - 8000:80

  fiberfy:
    image: "guifi/fiberfy:sails"
    environment:
      FIBERFY_UNIX_USER: fiberfy
      FIBERFY_GIT_REPO: https://github.com/guifi/fiberfy-server.git
    command: gosu fiberfy node --inspect=0.0.0.0:9229 app.js
    links:
      - database
    ports:
      - 1337:1337
      - 9229:9229
    volumes:
      - ./fiberfy-server:/usr/share/node/fiberfy

  gmaps:
    image: "guifi/guifimaps"
    environment:
      GUIFI_WEB: "guifi.net"
      FIBERFY_API: "fiberfy:1337"
      FIBERFY_LOGIN: "/auth/loginLDAP"
      FIBERFY_EXPORT: "/api/v1/export/all"
      LDAP_USERNAME: "${LDAP_USERNAME}"
      LDAP_PASSWORD: "${LDAP_PASSWORD}"
    links:
      - fiberfy
    ports:
      - 9000:80
    volumes:
      - ./guifimaps:/home/guifi/

volumes:
  guifi-web:
    external: false
