version: "2"
services:
  database:
    image: "mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: guifitest
      MYSQL_USER: guifi
      MYSQL_PASSWORD: guifi
    volumes:
      - ./database:/var/lib/mysql

  fiberfy:
    image: "guifi/fiberfy:sails"
    environment:
      FIBERFY_UNIX_USER: fiberfy
      FIBERFY_GIT_REPO: https://github.com/guifi/fiberfy-server.git
    links:
      - database
    ports:
      - 1337:1337
    volumes:
      - .:/usr/share/node/fiberfy
